### ISSUE TITLE
darkButtons property is not working on Android 13

### ISSUE THREAD

**Issue by Remskei** [hugotomazi/navigation-bar#12]
Hi,

It looks like darkButtons property is not working on Android 13. The navigation bar buttons are always white.
I have tried on Android 10 and it's working fine.

Is it possible to make it working on Android 13 ?

Thanks for your work 😄

**Comment by WilliamFischer** [comment]
Yes! I second this!

**Comment by sabereen** [comment]
https://developer.android.com/reference/android/view/View#setSystemUiVisibility(int)

> setSystemUiVisibility
> 
> This method was deprecated in API level 30. SystemUiVisibility flags are deprecated. Use [WindowInsetsController](https://developer.android.com/reference/android/view/WindowInsetsController) instead.

**Comment by f1ght4fun** [comment]
When is this going to be fixed !? Still having issues with darkButtons =\

I am trying on both Android 11 and 13. In both cases i am setting backgroundColor to white and darkButtons to true.
The background is white but buttons are invisible on the white background

PLease advise,

Thanks!

**Comment by hugotomazi** [comment]
Hello @f1ght4fun! On the next week i will release the fix. I need more time to evaluate another bug that will be fixed in the same release.

**Comment by hugotomazi** [comment]
Hello everyone, the new version has been published with the fix, please update to version 2.0.1.

**Comment by f1ght4fun** [comment]
Hi,

Its working for me fine now on Android 12 and 13, however all versions prior - it makes the background white but does not change the color of navigation buttons - so they are left being white on white.

Any ideas ?

**Comment by hugotomazi** [comment]
Hello @f1ght4fun. Can you add prints of both cases? In android API 30+ and 30- for us to validate? Which specific version did you test and see the abnormality?
