### ISSUE TITLE
Apply to just navigation bar

### ISSUE THREAD

**Issue by darinw** [hugotomazi/navigation-bar#17]
On Android `NavigationBar.setTransparency` affects the StatusBar

i am using `@capacitor/status-bar` & `@hugotomazi/capacitor-navigation-bar`

```typescript
StatusBar.setBackgroundColor({ color: 'blue' });
StatusBar.setStyle({ style: Style.Dark });
NavigationBar.setTransparency({ isTransparent: true });
```

This results in the NavigationBar acting as desired but the StatusBar is blue with the app content behind it.

Is is possible to only affect the NavigationBar?

**Comment by hugotomazi** [comment]
Hello! Which API version are you testing?

**Comment by fromage9747** [comment]
Even if you don't use the StatusBar plugin at all, the NavigationBar affects the Statusbar.
