### ISSUE TITLE
Capacitor 5 compatibility

### ISSUE THREAD

**Issue by mauricewegner** [hugotomazi/navigation-bar#18]
Would be great if this plugin could follow [the requirements](https://capacitorjs.com/docs/updating/plugins/5-0) to be compatible with Capacitor v5 as the stable version has now been released.

**Comment by ludonoel1** [comment]
When I click/ touch my app navigation bar is showed...
IS it normal, now ?
It wasn't the same behaviour with last version capacitor 4 /ionic 6

**Comment by hugotomazi** [comment]
> Would be great if this plugin could follow [the requirements](https://capacitorjs.com/docs/updating/plugins/5-0) to be compatible with Capacitor v5 as the stable version has now been released.

Thanks for your contribution @mauricewegner. Already merged and published in version 3.0.0.


> When I click/ touch my app navigation bar is showed... IS it normal, now ? It wasn't the same behaviour with last version capacitor 4 /ionic 6

This occurs in all apps. It is a native behavior of the operating system.
