### ISSUE TITLE
Support capacitor v6

### ISSUE THREAD

**Issue by rosostolato** [hugotomazi/navigation-bar#25]
I want to start using this plug-in but my app has already been moved to capacitor v6. Does it already support? Any plan to support in the next days?

**Comment by SvenBudak** [comment]
@hugotomazi please ^^

**Comment by Quasarman** [comment]
please

**Comment by usison-draeger** [comment]
@hugotomazi  We also need an update to capacitor v6. This plugin is great and we would like to keep on using it.

**Comment by hugotomazi** [comment]
Hello everyone, support added, please migrate to version 4.0.0 of the plugin using the command "npm install @hugotomazi/capacitor-navigation-bar@latest"

**Comment by Quasarman** [comment]
Hello @hugotomazi,

sorry to bother you again but you also need to update the `peerDependencies` inside the `package.json` otherwise I get an install error:

```
Found: @capacitor/core@6.1.0
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"^6.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^4.0.1 || ^5.0.0" from @hugotomazi/capacitor-navigation-bar@4.0.0
npm ERR! node_modules/@hugotomazi/capacitor-navigation-bar
npm ERR!   @hugotomazi/capacitor-navigation-bar@"4.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

And I rather not use `--force` when installing.

Thanks!

**Comment by hugotomazi** [comment]
Hi @Quasarman.
I uploaded a new version with the mentioned correction. In my tests it seems that the installation occurs normally. Can you test again?

**Comment by Quasarman** [comment]
Hello @hugotomazi,
works just fine now.
Thank you very much for the quick fix!

**Comment by usison-draeger** [comment]
@hugotomazi  Thanks for the quick fix.......very much appreciated !!!
