### ISSUE TITLE
missing HugotomaziCapacitorNavigationBar.podspec

### ISSUE THREAD

**Issue by ronfak** [hugotomazi/navigation-bar#5]
**HugotomaziCapacitorNavigationBar.podspec** was not installed during **npm install**. As a result I got this error :

```
[error] Analyzing dependencies
        [!] No podspec found for `HugotomaziCapacitorNavigationBar` in
        `../../node_modules/@hugotomazi/capacitor-navigation-bar`
```

I had to add the file manually to make it work.

**Comment by hugotomazi** [comment]
Hello @ronfak , fixed NPM package! Please update to version 1.1.1.
Thanks!
